stages:
  - setup
  - build
  - deploy

cache:
  paths:
    - node_modules/

setup:
  image: registry.blitzhub.io/ng_cli_karma
  stage: setup
  script:
    - npm install

build:
  image: registry.blitzhub.io/ng_cli_karma
  stage: build
  artifacts:
    paths:
      - dist
  script:
    - npm install
    - npm run build
  dependencies:
    - setup

#deploy-exbio:
#  image: registry.blitzhub.io/docker
#  stage: deploy
#  only:
#    - master
#  services:
#    - name: registry.blitzhub.io/docker:dind
#      alias: docker
#  variables:
#    CONTAINER_HOSTNAME: docker
#  before_script:
#    - docker info
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#  script:
#    - docker build -t gitlab.lrz.de:5005/netex/drugstone-website -f ./Dockerfile .
#    - docker push gitlab.lrz.de:5005/netex/drugstone-website
#  dependencies:
#    - build

deploy-uhh:
  image: registry.blitzhub.io/docker
  stage: deploy
  only:
    - master
  services:
    - name: registry.blitzhub.io/docker:dind
      alias: docker
  variables:
    CONTAINER_HOSTNAME: docker
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t gitlab.lrz.de:5005/netex/drugstone-website -f ./Dockerfile-rrz .
    - docker push gitlab.lrz.de:5005/netex/drugstone-website
  dependencies:
    - build
