FROM node:22.12.0-alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN mv src_dev/* src
RUN mv src/app/configs/normal.js src/app/configs/default.js
RUN rm -rf nginx

RUN npm run build -- --base-href=./

FROM nginx

COPY --from=build-stage /app/dist/website/browser/ /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/

EXPOSE 80
